# Site settings
title: 王超的独立博客
SEOTitle: 王超的独立博客 | WangChao Blog
header-img: img/home-bg.jpg
email: 1490789115@qq.com
description: "王超的独立博客"
keyword: "王超, 王超, 王超的博客, 王超的独立博客, Blog, 博客, 个人网站"
url: "www.wangchaochao.top"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     wangchao149
zhihu_username:     wangchao149
github_username:    whik
#twitter_username:  beyondsgy
#facebook_username:  beyondsgy



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: false                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
#duoshuo_username: shaoguoji
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                     # set to false if you want to use Comment without Sharing

# Youyan settings
#youyan_username: shaoguoji
# Share component is depend on Comment so we can NOT use share only.
#youyan_share: true                     # set to false if you want to use Comment without Sharing


# gentie settings
# gentie_product_key: 265c82c8980f42c18a066337c8ab26bc
# Share component is depend on Comment so we can NOT use share only.
# gentie_share: false  

# gitment settings
gitment_share: true  
gitment_username: whik
gitment_repo: whik.github.io
gitment_client_id: 8e11bd6af0a339d8007f
gitment_client_secret: f257dd2a71e396ad57aa9aef0ea3ab85331e006b


# Analytics settings
#Baidu Analytics
#ba_track_id: aa77dd1af62bf0b3cb69ac8ee616f047
ba_track_id: 8426de655a9a773efd3509a0c388c8a7 
# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "调调板子，写写代码，生活还是这么美好。"
sidebar-avatar: /img/avatar-wcc.png  # use absolute URL, seeing it's used in both `/` and `/about/`
# old pic http://odaps2f9v.bkt.clouddn.com/17-2-18/70710645-file_1487416001693_3e6.png


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "CSDN",
        href: "https://blog.csdn.net/whik1194"
    },
    {
        title: "博客园",
        href: "https://www.cnblogs.com/whik"
    },
    {
        title: "我的公众号",
        href: "https://wcc-blog.oss-cn-beijing.aliyuncs.com/img/%E6%B1%82%E5%85%B3%E6%B3%A8.jpg"
    },
    {
        title: "物联网|吴川斌的博客",
        href: "http://www.mr-wu.cn/"
    }    

]
